[project]
name = "habits"
version = "1.0.0"
description = "Habits Tracker - A simple habit tracking application"

[build]
entry = "main.kry"
targets = ["desktop", "web"]
frontend = "kry"
output_dir = "dist"

[targets.web]
output = "html"

[targets.desktop]
renderer = "sdl3"

[install]
mode = "copy" 

[dev]
hot_reload = true
port = 3000
auto_open = true

[plugins.kryon]
path = "../../KryonLabs/kryon-plugins"
use  = ["math", "storage", "datetime","uuid"]